apiVersion: v1
kind: Service
metadata:
  name: backend-rssfeed
  labels:
    app: backend-rssfeed

spec:
  ports:
  - name: "http"
    port: 8000
    targetPort: 8000
  selector:
    app: backend-rssfeed