version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=${REPO_ECR}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # - docker build -t $REPOSITORY_URI:latest .
      # - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker build -t cap-api-user cap-api-user
      - docker build -t cap-api-rssfeed cap-api-rssfeed
      - docker build -t rss-frontend rss-frontend
      - docker build -t cap-reverseproxy cap-reverseproxy
      - docker tag cap-api-user aisamuel/cap-api-user:v1
      - docker tag cap-api-rssfeed aisamuel/cap-api-rssfeed:v1
      - docker tag rss-frontend aisamuel/rss-frontend:v1
      - docker tag cap-reverseproxy aisamuel/cap-reverseproxy:v1
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      # - docker push $REPOSITORY_URI:latest
      # - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push aisamuel/cap-api-user:v1
      - docker push aisamuel/cap-api-rssfeed:v1
      - docker push aisamuel/cap-reverseproxy:v1
      - docker push aisamuel/rss-frontend:v1