version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      # - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - $(aws ecr get-login $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY)
      - REPOSITORY_URI=${REPO_ECR}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # - docker build -t $REPOSITORY_URI:latest .
      # - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker build -t $REPOSITORY_URI:cap-api-user cap-api-user
      - docker build -t $REPOSITORY_URI:cap-api-rssfeed cap-api-rssfeed
      - docker build -t $REPOSITORY_URI:rss-frontend rss-frontend
      - docker build -t $REPOSITORY_URI:cap-reverseproxy cap-reverseproxy
      - docker tag $REPOSITORY_URI:cap-api-user $REPOSITORY_URI:cap-api-user:v1
      - docker tag $REPOSITORY_URI:cap-api-rssfeed $REPOSITORY_URI:cap-api-rssfeed:v1
      - docker tag $REPOSITORY_URI:rss-frontend $REPOSITORY_URI:rss-frontend:v1
      - docker tag $REPOSITORY_URI:cap-reverseproxy $REPOSITORY_URI:cap-reverseproxy:v1
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      # - docker push $REPOSITORY_URI:latest
      # - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:cap-api-user
      - docker push $REPOSITORY_URI:cap-api-rssfeed
      - docker push $REPOSITORY_URI:cap-reverseproxy
      - docker push $REPOSITORY_URI:rss-frontend
      - docker push $REPOSITORY_URI:cap-api-user:v1
      - docker push $REPOSITORY_URI:cap-api-rssfeed:v1
      - docker push $REPOSITORY_URI:cap-reverseproxy:v1
      - docker push $REPOSITORY_URI:rss-frontend:v1