version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-rssfeed
  backend-user:
    image: cap-api-user
    volumes:
      - ./cap-api-user/:/home/app/webapp
      - $HOME/.aws:/root/.aws
    environment:
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      PGHOST: $PGHOST
      PGDATABASE: $PGDATABASE
      PGPORT: $PGPORT
      DATABASE: $DATABASE
      URL: "http://localhost:8100"
    ports:
      - "8001:8000"

  backend-rssfeed:
    image: cap-api-rssfeed
    volumes:
      - ./cap-api-rssfeed/:/home/app/webapp
      - $HOME/.aws:/root/.aws
    environment:
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      PGHOST: $PGHOST
      PGDATABASE: $PGDATABASE
      PGPORT: $PGPORT
      DATABASE: $DATABASE
      URL: "http://localhost:8100"
    ports:
      - "8000:8000"
  # frontend:
  #   image: udagram-frontend:local
  #   ports:
  #     - "8100:80"