# .circleci/config.yml file
version: 2.1

jobs:
  build:            # job name
    docker:         # executor type
      - image: cimg/base:current # Docker image that installs Docker and has Git,
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: echo "No need to install anything. \n Just build and push the Docker image."
      - run:
          name: Build and push Docker image
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            docker build -t cap-api-feed ./cap-api-feed  
            docker build -t cap-api-rssfeed ./cap-api-rssfeed
            docker build -t rss-frontend ./rss-frontend
            docker build -t cap-reverseproxy ./cap-reverseproxy
            docker tag cap-api-feed aisamuel/cap-api-feed:v1
            docker tag cap-api-rssfeed aisamuel/cap-api-rssfeed:v1
            docker tag rss-frontend aisamuel/rss-frontend:v1
            docker tag cap-reverseproxy aisamuel/cap-reverseproxy:v1
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push aisamuel/cap-api-feed:v1
            docker push aisamuel/cap-api-rssfeed:v1
            docker push aisamuel/cap-reverseproxy:v1
            docker push aisamuel/rss-frontend:v1