export const config = {
  'username': "samuelnewdb",
  'password': "Samuel65#*#",
  'database': "postgres",
  'host': "samuelnewdb.cwb1fio8s3ex.us-east-1.rds.amazonaws.com",
  'dialect': 'postgres',
  'aws_region': "us-east-1",
  'aws_profile': "default",
  'aws_media_bucket': "test-2345679-sam-dev",
  'url': "http://aa9072fece3c04e70a525b3a3ca761e6-1574223951.us-east-1.elb.amazonaws.com",
  'jwt': {
    'secret': "testing",
  },
  // 'username': process.env.POSTGRES_USERNAME,
  // 'password': process.env.POSTGRES_PASSWORD,
  // 'database': process.env.POSTGRES_DB,
  // 'host': process.env.POSTGRES_HOST,
  // 'dialect': 'postgres',
  // 'aws_region': process.env.AWS_REGION,
  // 'aws_profile': process.env.AWS_PROFILE,
  // 'aws_media_bucket': process.env.AWS_BUCKET,
  // 'url': process.env.URL,
  // 'jwt': {
  //   'secret': process.env.JWT_SECRET,
  // },
};
